export { useAnimalsQuery } from './useAnimalsQuery';
export { useAnimalQuery } from './useAnimalQuery';
export { useAddAnimalMutation } from './useAddAnimalMutation';
export { useAddSpiderMutation, useAddMultipleSpidersMutation } from './useAddSpiderMutation';
export type { SpiderData } from './useAddSpiderMutation';
export { useUpdateAnimalMutation } from './useUpdateAnimalMutation';
export { useDeleteAnimalMutation } from './useDeleteAnimalMutation';
export { useDeleteMultipleAnimalsMutation } from './useDeleteMultipleAnimalsMutation';
export { useMarkDeceasedMutation } from './useMarkDeceasedMutation';
export { useUploadPhotosMutation } from './useUploadPhotosMutation';
export { useDeletePhotoMutation } from './useDeletePhotoMutation';
export { useSetMainPhotoMutation } from './useSetMainPhotoMutation';
